base_app/urls.py
from django.urls import path, include
from . import views

app_name = 'base_app'
urlpatterns = [
    path('', views.index, name='index')

]

partners_app/api/urls.py
from rest_framework import routers
from django.conf.urls import include
from django.urls import path

from . import views

router = routers.DefaultRouter()
router.register('clients', views.ClientViewSet)
router.register('employees', views.ClientViewSet)
router.register('identity_documents', views.IdentityDocumentViewSet)


urlpatterns = [
    path('', include(router.urls)),
    #path('clients_list', views.ClientViewSet.as_view({'get':'list'}), name='clients_list_api' ),

]

partners_app/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView

from . import views
from .models import Client, Employee, IdentityDocument
from .forms import ClientForm, EmployeeForm

app_name = 'partners_app'




urlpatterns = [
    path('api/', include('partners_app.api.urls')),

    path('client_list/', views.ClientListView.as_view(), name='client_list'),
    path('employee_list/', views.EmployeeListView.as_view(), name='employee_list'),
    path('new_client/', views.ClientCreateView.as_view(), name='new_client'),
    path('detail_client/<int:pk>/', views.ClientUpdateView.as_view(), name='detail_client'),
    path('new_employee/', views.EmployeeCreateView.as_view(), name='new_employee'),
    path('detail_employee/<int:pk>/', views.EmployeeUpdateView.as_view(), name='detail_employee'),
    path('delete_employee/<int:pk>/', views.EmployeeDeleteView.as_view(),name='delete_employee'),
    path('delete_client/<int:pk>/', views.ClientDeleteView.as_view(), name='delete_client'),
    path('get_identity_document_form/', views.GetIdentityDocumentForm.as_view(),name='new_identity_document'),
]

sports_organization/urls.py
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path


from sports_organization import settings
from partners_app import views

urlpatterns = [
    path('', include('base_app.urls', namespace='base_app')),
    path('admin/', admin.site.urls),
    path('services/', include('services_app.urls', namespace='services_app')),
    path('partners/', include('partners_app.urls', namespace='partners_app')),


]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

partners_app/models.py
from datetime import datetime

from PIL import Image
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.urls import reverse

class IdentityDocument(models.Model):
    document_name = models.CharField(max_length=32, blank=False, null=False, verbose_name='Наименование документа')
    document_serial = models.CharField(max_length=32, blank=False, null=False, verbose_name='Серия документа')
    document_number = models.CharField(max_length=32, blank=False, null=False, verbose_name='Номер документа')
    date_of_issue = models.DateField(verbose_name='Дата выдачи')
    date_of_validity = models.DateField(verbose_name='Действителен до')
    issuing_authority = models.CharField(max_length=256, blank=False, null=False, verbose_name='Орган выдавший документ')

    class Meta:
        verbose_name = 'Документ удостоверяющий личность'
        verbose_name_plural = 'Документы удостоверяющие личность'

    def __str__(self):
        return ('{} {} {}'.format(self.document_name, self.document_serial, self.document_number))


class AbstractPartner(models.Model):
    last_name = models.CharField(max_length=256, blank=False, null=False, verbose_name="Фамилия")
    first_name = models.CharField(max_length=256, blank=False, null=False, verbose_name="Имя")
    patronymic = models.CharField(max_length=256, blank=False, null=False, verbose_name="Отчество")
    birthday = models.DateField(verbose_name="Дата рождения")
    personal_number = models.CharField(max_length=14, blank=True, null=True, verbose_name="Личный номер")
    identity_document = models.OneToOneField('IdentityDocument', verbose_name="Документ удостоверяющий личность",
                                             on_delete=models.PROTECT, blank=True, null=True)
    image = models.ImageField(upload_to='image/partners_app/%Y/%m/%d/', default=None, blank=True, null=True,
                              verbose_name='Фотография')


class Client (AbstractPartner):
    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"

    def __str__(self):
        return '{} {} {}'.format(self.last_name, self.first_name, self.patronymic)

    def get_absolute_url(self):
        return reverse('partners_app:detail_client', args=[self.id])


class Employee(AbstractPartner):
    date_of_employment = models.DateField(verbose_name='Дата приема на работу')
    date_of_dismissal = models.DateField(verbose_name='Дата увольнения', blank=True, null=True, default=None)

    class Meta:
        verbose_name = "Сотрудник"
        verbose_name_plural = "Сотрудники"

    def __str__(self):
        return '{} {} {}'.format(self.last_name, self.first_name, self.patronymic)

    def get_absolute_url(self):
        return reverse('partners_app:detail_employee', args=[self.id])

partners_app/forms.py
from django import forms
from .models import Client, Employee, IdentityDocument, AbstractPartner

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ClientForm, self).__init__(*args, **kwargs)
        using_identity_document = [obj.identity_document.id for obj in AbstractPartner.objects.filter(identity_document_id__isnull=False)]
        if not self.instance.identity_document:
            self.fields['identity_document'].queryset = IdentityDocument.objects.exclude(id__in=using_identity_document)
        else:
            self.fields['identity_document'].queryset = IdentityDocument.objects.filter(id=self.instance.identity_document.id)


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EmployeeForm, self).__init__(*args, **kwargs)
        using_identity_document = [obj.identity_document.id for obj in AbstractPartner.objects.filter(identity_document_id__isnull=False)]
        if not self.instance.identity_document:
            self.fields['identity_document'].queryset = IdentityDocument.objects.exclude(id__in=using_identity_document)
        else:
            self.fields['identity_document'].queryset = IdentityDocument.objects.filter(id=self.instance.identity_document.id)



# class IdentityDocumentForm(forms.ModelForm):
#     class Meta:
#         model = IdentityDocument
#         fields = "__all__"

partners_app/api/views.py
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from partners_app.api.serializers import SerializerClient, SerializerEmployee, SerialazerIdentityDocument
from ..models import Client, Employee, IdentityDocument



# Create your views here.

class ClientViewSet(ModelViewSet):
    queryset = Client.objects.all()
    serializer_class = SerializerClient


class EmployeeViewSet(ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = SerializerEmployee


class IdentityDocumentViewSet(ModelViewSet):
    queryset = IdentityDocument.objects.all()
    serializer_class = SerialazerIdentityDocument

partners_app/views.py
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView,UpdateView,DeleteView,ListView
from rest_framework.viewsets import ModelViewSet

from partners_app.api.serializers import SerializerClient
from partners_app.forms import EmployeeForm, ClientForm
from .models import Client, Employee, IdentityDocument
from .utils import get_data_to_field


# Create your views here.

class PartnersListView(ListView):
    template_name = 'partners_app/partners_list.html'
    context_object_name = 'partners'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(PartnersListView, self).get_context_data(**kwargs)
        context['partner_type'] = str(self.model).split('.')[-1][:-2].lower()
        return context


class ClientListView(PartnersListView):
    model = Client


class EmployeeListView(PartnersListView):
    model = Employee


class PartnerCreateView(CreateView):
    template_name = 'partners_app/detail_partner.html'

    def get_context_data(self, **kwargs):
        context = super(PartnerCreateView, self).get_context_data(**kwargs)
        context['partner_type'] = str(self.model).split('.')[-1][:-2].lower()
        return context


class ClientCreateView(PartnerCreateView):
    model = Client
    form_class = ClientForm


class EmployeeCreateView(PartnerCreateView):
    model = Employee
    form_class = EmployeeForm


class PartnerUpdateView(UpdateView):
    template_name = 'partners_app/detail_partner.html'

    def get_context_data(self, *args, **kwargs):
        context = super(PartnerUpdateView, self).get_context_data(*args, **kwargs)
        partner_type = str(self.model).split('.')[-1][:-2].lower()
        context['partner_type'] = partner_type
        return context


class ClientUpdateView(PartnerUpdateView):
    model = Client
    form_class = ClientForm

class EmployeeUpdateView(PartnerUpdateView):
    model = Employee
    form_class = EmployeeForm


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('partners_app:client_list')


class EmployeeDeleteView(DeleteView):
    model = Employee
    success_url = reverse_lazy('partners_app:employee_list')

class GetIdentityDocumentForm(CreateView):
    model = IdentityDocument
    fields = '__all__'
    template_name= 'partners_app/snippets/form_snippet.html'

partners_app/templates/partners_app/client_confirm_delete.html
{% include 'partners_app/snippets/confirm_delete_snippet.html' %}

partners_app/templates/partners_app/detail_partner.html
{% extends 'base_app/base.html' %}
{% load staticfiles %}
{% block body %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'partners_app/css/modal_form.css' %}">
    <div class="container">
        <div class="row">
            <div class="offset-3 col-lg-6" >
                <form id="partner_detail_form" method="post" enctype="multipart/form-data" class=""
                      {% if partner_id %}
                        action="{{ form.instance.get_absolute_url }}"
                      {% endif %}>
                    {% csrf_token %}
                    {{ form.as_p}}
                    <p><button name="submit" type="submit">Сохранить</button></p>
                </form>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="{% static 'base_app/js/django_form.js' %}"></script>
    <script type="text/javascript" >
        bootstrap_form('#partner_detail_form');
        django_date_to_datefield('#id_birthday');
        {% ifequal partner_type 'employee'%}
            django_date_to_datefield('#id_date_of_dismissal');
            django_date_to_datefield('#id_date_of_employment');
        {% endifequal %}
    </script>
    <script type="text/javascript" src="{% static 'partners_app/js/add_identity_document.js' %}"></script>
    <script>add_element('#id_identity_document', "{% url 'partners_app:new_identity_document' %}")</script>

{% endblock %}

partners_app/templates/partners_app/employee_confirm_delete.html
{% include 'partners_app/snippets/confirm_delete_snippet.html' %}

partners_app/templates/partners_app/partners_list.html
{% extends 'base_app/base.html' %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-offset-2 col-lg-8 ">
                <div class="table-responsive ">
                    <table  id="table" class="table table-bordered">
                    {% for partner in partners %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            {% if partner_type == 'client' %}
                                <td><a href="{% url 'partners_app:detail_client' partner.id %}">{{ partner.last_name }}</a></td>
                                {% else %}
                                <td><a href="{% url 'partners_app:detail_employee' partner.id %}">{{ partner.last_name }}</a></td>
                            {% endif %}

                            <td>{{ partner.first_name }}</td>
                            <td>{{ partner.patronymic }}</td>
                            <td>{{ partner.birthday|date:'d.m.Y' }}</td>
                            {% if partner_type == 'client' %}
                            <td><a href="{% url 'partners_app:delete_client' partner.id %}">delete</a></td>
                            {% else %}
                            <td><a href="{% url 'partners_app:delete_employee' partner.id %}">delete</a></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </table>
                {% if paginator.num_pages > 1 %}
                    <div id="pagination" style="display: inline-block">
                        {% if page_obj.number > 1 %}
                            <div id="first_page" style="display: inline-block">
                                <a href="{{ request.path }}?page=1">first</a>
                            </div>
                        {% endif %}
                        {% if page_obj.has_previous %}
                            <div id="previus_page" style="display: inline-block"><a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">&lt;</a></div>
                        {% endif %}
                            <div id="num_page" style="display: inline-block">
                                {% for pn in paginator.page_range %}
                                    {% if not forloop.first %}
                                        &nbsp;&nbsp;|&nbsp;&nbsp;
                                    {% endif %}
                                    {% if page_obj.number != pn %}
                                        <a href="{{ request.path }}?page={{ pn }}">{{ pn }}</a>
                                        {% else %}
                                        {{ pn }}
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% if page_obj.has_next %}
                            <div id="next_page" style="display: inline-block">
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">&gt;</a>
                            </div>
                            <div id="last_page" style="display: inline-block">
                                <a href="{{ request.path }}?page={{ page_obj.paginator.num_pages }}">last</a>
                            </div>
                        {% endif %}
                    </div>
                {% endif %}
                <div id="btn">
                    {% if partner_type == 'client' %}
                        <button class="btn" onclick="location.href = '{% url "partners_app:new_client" %}'">Добавить клиента</button>
                    {% else %}
                        <button class="btn" onclick="location.href = '{% url "partners_app:new_employee" %}'">Добавить сотрудника</button>
                    {% endif%}
                </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}