base_app/urls.py
from django.urls import path, include
from . import views

app_name = 'base_app'
urlpatterns = [
    path('', views.index, name='index')

]

partners_app/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView

from . import views
from .models import Client, Employee, IdentityDocument
from .forms import ClientForm, EmployeeForm

app_name = 'partners_app'




urlpatterns = [
    path('api/', include('partners_app.api.urls')),

    path('client_list/', views.ClientListView.as_view(), name='client_list'),
    path('employee_list/', views.EmployeeListView.as_view(), name='employee_list'),
    path('new_client/', views.ClientCreateView.as_view(), name='new_client'),
    path('detail_client/<int:pk>/', views.ClientUpdateView.as_view(), name='detail_client'),
    path('new_employee/', views.EmployeeCreateView.as_view(), name='new_employee'),
    path('detail_employee/<int:pk>/', views.EmployeeUpdateView.as_view(), name='detail_employee'),
    path('delete_employee/<int:pk>/', views.EmployeeDeleteView.as_view(),name='delete_employee'),
    path('delete_client/<int:pk>/', views.ClientDeleteView.as_view(), name='delete_client'),
    path('get_identity_document_form/', views.GetIdentityDocumentForm.as_view(),name='new_identity_document'),
]

sports_organization/urls.py
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path


from sports_organization import settings
from partners_app import views

urlpatterns = [
    path('', include('base_app.urls', namespace='base_app')),
    path('admin/', admin.site.urls),
    path('services/', include('services_app.urls', namespace='services_app')),
    path('partners/', include('partners_app.urls', namespace='partners_app')),


]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base_app/models.py
from django.db import models

# Create your models here.

base_app/views.py
import datetime

from django.shortcuts import render


def index(request):
    return render(request, 'base_app/base.html')

base_app/templates/base_app/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    {% csrf_token %}
    <script type="text/javascript">var csrf = $(document).find("[name='csrfmiddlewaretoken']").val()</script>

    <title>{% block title %}Управление услугами{% endblock title%}</title>

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'partners_app:client_list' %}">Список клиентов</a>
              </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'partners_app:employee_list' %}">Список сотрудников</a>
                </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>
  </head>
  <body>
    {% load staticfiles %}

    {% block body %}

    {% endblock body%}

  </body>
</html>

base_app/templates/base_app/base_whithout_navbar.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <title>Управление услугами</title>
  </head>
  <body>
    {% load staticfiles %}
    {% block body %}

    {% endblock body%}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    {% csrf_token %}
    <script type="text/javascript">var csrf = $(document).find("[name='csrfmiddlewaretoken']").val()</script>
  </body>
</html>